version: "3.9"

services:

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "6541:5432"
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  main-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm_main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "6540:5432"
    volumes:
      - main-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  stats-server:
    build: ./stats-service/server
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:9090/actuator/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  ewm-service:
    build: ./ewm-main-service
    depends_on:
      main-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/ewm_main
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      STATS_SERVICE_URL: http://stats-server:9090
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/actuator/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 24
      start_period: 15s

volumes:
  stats-db-data:
  main-db-data:
