server.port: 8080
spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lower-case-service-id: true
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

management.endpoints.web.exposure.include: health,info
