server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:stat
    username: stat
    password: stat
