spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:stats-db
    username: postgres
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect