server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: admin_category
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**

        - id: public_category
          uri: lb://event-service
          predicates:
            - Path=/categories/**

        - id: admin_comment
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**

        - id: private_comment
          uri: lb://comment-service
          predicates:
            - Path=/users/{userId}/comments/**

        - id: public_comment
          uri: lb://comment-service
          predicates:
            - Path=/comments/**

        - id: admin_compilation
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**

        - id: public_compilation
          uri: lb://event-service
          predicates:
            - Path=/compilations/**

        - id: admin_event
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**

        - id: private_event
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/events/**

        - id: public_event
          uri: lb://event-service
          predicates:
            - Path=/events/**

        - id: participation_request
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**

        - id: user
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**